### PR TITLE
add cli (GSI-658) 

### PR DESCRIPTION
**Pull request by KerstenBreuer**
```
Added CLI commands for:
- validation a datapack against a schemapack
- checking the compliance of a document with the datapack or schemapack spec
```
More commands to come, adding this early to allow the #24 PR to add a cli.

### CODE REVIEW

**Comment by KerstenBreuer** [comment]
Need to fix, now that #23 is merged. Will do in a second

**Comment by KerstenBreuer** [comment]
Now it is ready

**Review by lkuchenb — APPROVED** [review]
Look good to me! A minor though, it would be great to get rid of the pydantic URLs in the messages.

**Comment by KerstenBreuer** [comment]
> Look good to me! A minor thought, it would be great to get rid of the pydantic URLs in the messages.

Indeed, right now, the exception are coming directly from pydantic. And in general it does a really good job showing error messages for a wide range of issues. Thus t might not be worth to try and hide the pydantic message. Nevertheless, a good item for the refactoring list. Will you add it?

**Review by sbilge — APPROVED** [review]

**Comment by lkuchenb** [comment]
@KerstenBreuer I've added a patch that changes the default pydantic behavior in case schemapack is invoked via CLI but leaves the default behaviour otherwise in 72f87d4 - would that be okay with you?

**Review by lkuchenb — APPROVED** [review]

**Comment by KerstenBreuer** [comment]
Hi @lkuchenb, could we discuss this in a separate PR/meeting? (I think I misunderstood that you generally didn't like the pydantic errors, however, now I see you comment was specifically about the URLs).

**Comment by lkuchenb** [comment]
Sure

**Review by lkuchenb — APPROVED** [review]

**Pull request merged**
